In [19]:
from pycoingecko import CoinGeckoAPI
import pandas as pd
cg = CoinGeckoAPI()
btc_data = cg.get_coin_market_chart_by_id(id='bitcoin',vs_currency='usd', days=10)
                                          
btc_data

{'prices': [[1751382199379, 105922.44787606507],
  [1751385660193, 105993.55330893262],
  [1751389423274, 106118.54247337948],
  [1751393020774, 106274.38401781903],
  [1751396624280, 105781.26913424997],
  [1751400227235, 105558.1795216201],
  [1751403681313, 105906.81152814372],
  [1751407383098, 105799.53888074443],
  [1751411075819, 105729.30337893893],
  [1751414620619, 105671.37564921292],
  [1751418214352, 105430.0699189044],
  [1751421824475, 105713.62467631401],
  [1751425407523, 105874.88851628656],
  [1751429016864, 106192.61908374571],
  [1751432613161, 106361.82729453016],
  [1751436215652, 106637.67190982355],
  [1751439824385, 107011.09654749483],
  [1751443397571, 107154.9395995294],
  [1751446957875, 107723.86722863429],
  [1751450646622, 107660.59607867351],
  [1751454033906, 107804.12497574199],
  [1751458098708, 107491.88894045986],
  [1751461433908, 107379.01121426729],
  [1751465042114, 107768.94266033295],
  [1751468638496, 108049.63995066886],
  [1751472245095, 108719.610384343],
  [1751475840542, 109524.79595664969],
  [1751479456405, 109130.5190650251],
  [1751482892256, 109512.18661959792],
  [1751486619434, 109608.34454475196],
  [1751490126451, 109245.4846693272],
  [1751493832889, 109498.2520966054],
  [1751497429210, 109172.67593813807],
  [1751501037652, 108876.33080471942],
  [1751504604369, 108967.92721160711],
  [1751508210639, 109057.66813145111],
  [1751511839165, 108725.13872565234],
  [1751515447606, 108708.78299547141],
  [1751519026793, 108833.55583203761],
  [1751522638663, 109362.57592106404],
  [1751526187470, 109508.37405742171],
  [1751529648264, 109330.97520438877],
  [1751533435412, 109459.70029882406],
  [1751536945911, 110005.50910443353],
  [1751540625434, 109847.4168916494],
  [1751544224963, 109630.73581504704],
  [1751547834603, 109153.29814972244],
  [1751551432148, 110306.89134124944],
  [1751555022935, 109729.9935709418],
  [1751558621741, 109173.44604642507],
  [1751562237504, 109389.26849358118],
  [1751565850945, 109585.31645185596],
  [1751569413058, 109666.14210713198],
  [1751572849130, 109824.37702950215],
  [1751576534402, 109930.53464903968],
  [1751580423581, 109844.89968138716],
  [1751583825545, 109740.8804104662],
  [1751587427301, 109602.20483914016],
  [1751591042281, 109521.73257176802],
  [1751594616616, 109547.54407846669],
  [1751598244301, 109217.0131197897],
  [1751601826980, 109275.17468549927],
  [1751605421725, 109025.36368252295],
  [1751609034555, 109089.33208686361],
  [1751612626987, 109032.51038477475],
  [1751616234841, 108782.58283541955],
  [1751619828086, 108807.55454160174],
  [1751623352769, 108991.71506309851],
  [1751627047047, 108939.69078406061],
  [1751630625771, 108947.60919794154],
  [1751634229513, 108779.55203760674],
  [1751637814783, 108080.14201247365],
  [1751641419941, 107875.12083035668],
  [1751645049093, 107683.37789325003],
  [1751648652227, 107663.19129939807],
  [1751652227815, 107902.85107452174],
  [1751655704764, 107587.36663162945],
  [1751659437396, 107474.62184599855],
  [1751663036890, 107739.19455526027],
  [1751666634074, 107938.45487234791],
  [1751670234072, 108260.04743409023],
  [1751673839940, 108015.91918796576],
  [1751677439910, 108221.98940035238],
  [1751680938155, 107985.24239548545],
  [1751684495201, 108080.69280477084],
  [1751688221595, 108191.01953980554],
  [1751691834549, 108219.77537727766],
  [1751695420331, 108170.0457987202],
  [1751698916373, 108268.47699607356],
  [1751702606207, 108043.83026863528],
  [1751706087258, 108026.86222614744],
  [1751709833677, 108099.40089057873],
  [1751713419581, 108159.84070504257],
  [1751717029684, 108174.64433643119],
  [1751720620496, 108158.506028589],
  [1751724208927, 108144.87788500875],
  [1751727831772, 108203.39074380611],
  [1751731408718, 108079.8732020311],
  [1751735051791, 108094.12112068693],
  [1751738484124, 108092.79362360307],
  [1751742229277, 108029.0012528044],
  [1751745845024, 108146.47997496236],
  [1751749405719, 108114.23616442076],
  [1751753016417, 108106.83166939252],
  [1751756630380, 108207.50672837593],
  [1751760237122, 108216.01621122604],
  [1751763725859, 108221.01364556968],
  [1751767395048, 108188.97421027656],
  [1751771032271, 108135.70188140584],
  [1751774627687, 108062.4485216917],
  [1751778045097, 108009.16769430414],
  [1751781812460, 108023.5612158881],
  [1751785313067, 108153.62729175891],
  [1751788872032, 108066.6287549658],
  [1751792623601, 108018.4761783963],
  [1751796050016, 107924.37145127529],
  [1751799729500, 108014.15265059208],
  [1751803431499, 108079.78827579075],
  [1751807023969, 108226.77823782979],
  [1751810644610, 108852.24281809523],
  [1751814049792, 108881.00285870154],
  [1751817822914, 108842.00463607795],
  [1751821451508, 108873.26682711164],
  [1751825034782, 108922.67195979225],
  [1751828641993, 108465.20961302417],
  [1751832234195, 108519.48830047643],
  [1751835840385, 108725.7506679581],
  [1751839381563, 109190.07810038677],
  [1751842831172, 109273.0167998506],
  [1751846610134, 109222.28203144151],
  [1751850233615, 108884.83919643541],
  [1751853829846, 109040.0364988704],
  [1751857419879, 109391.49731870665],
  [1751861306141, 109426.41237562221],
  [1751864614997, 109141.4662335669],
  [1751868147940, 109060.68873662295],
  [1751871698338, 108794.72246665078],
  [1751875413507, 109055.95982919865],
  [1751879018342, 108998.57079779266],
  [1751882618255, 108837.9695137941],
  [1751886274959, 108691.18135702463],
  [1751889803015, 108648.14015695457],
  [1751893426730, 108343.93368483889],
  [1751897026463, 108435.95739697783],
  [1751900445425, 108221.22050375078],
  [1751904199912, 108344.8309023719],
  [1751907827708, 107980.79962801684],
  [1751911426215, 107948.58904902542],
  [1751915031772, 107962.37308418423],
  [1751918641948, 108109.17303658143],
  [1751922243764, 107930.88282581135],
  [1751925823475, 108167.2213745081],
  [1751929419629, 108032.89177796259],
  [1751933029854, 108294.14789727505],
  [1751936613192, 108342.41323441773],
  [1751940240840, 107869.45480419397],
  [1751943799526, 107720.02901194381],
  [1751947428123, 107920.48670870182],
  [1751951027424, 108007.50427589758],
  [1751954616593, 108192.3965120717],
  [1751958020004, 108322.00619043256],
  [1751961829826, 108449.96409499412],
  [1751965388068, 108276.76542049045],
  [1751968965747, 108458.1597217873],
  [1751972620158, 108843.03766504247],
  [1751976230153, 108772.6214172488],
  [1751979833973, 108904.87395651502],
  [1751983245426, 109073.07144728328],
  [1751987026192, 108406.1743477702],
  [1751990639516, 108269.04717656305],
  [1751994208603, 108416.67394108746],
  [1751997846596, 108941.07172577523],
  [1752001445284, 109116.14147377446],
  [1752005042558, 108784.86962448058],
  [1752008622474, 108675.35707886492],
  [1752012184038, 108930.28353025016],
  [1752015838904, 108920.19114415902],
  [1752019436139, 108945.70903639354],
  [1752023035281, 108962.4725608281],
  [1752026647713, 108795.96256571825],
  [1752030196564, 108649.69348045423],
  [1752033802905, 108382.60401320309],
  [1752037370113, 108542.06540414323],
  [1752040993182, 108775.99214179988],
  [1752044636700, 108835.8966583524],
  [1752048124359, 108712.30310967196],
  [1752051627281, 108699.69913613351],
  [1752055255077, 108769.59937353026],
  [1752059005652, 108873.6901631303],
  [1752062606517, 109082.59555008526],
  [1752066037275, 109433.07396636377],
  [1752069838442, 109416.18664111895],
  [1752073439773, 108843.27368623985],
  [1752076997051, 109069.47853205416],
  [1752080604519, 109408.0230263172],
  [1752084231404, 109153.42774820444],
  [1752087831035, 109540.10975348887],
  [1752091427121, 111741.51191522085],
  [1752095020133, 110751.64956943537],
  [1752098597685, 110968.68404114945],
  [1752102230288, 111385.38257570405],
  [1752106089165, 111309.18837297094],
  [1752109421919, 111007.43750593303],
  [1752113036247, 111287.54047974612],
  [1752116621604, 111254.00945356322],
  [1752120223801, 111090.86770485823],
  [1752123820774, 111167.06861213944],
  [1752127434856, 111103.52646439127],
  [1752131038190, 111269.67232490583],
  [1752134460301, 111255.27854000233],
  [1752138214712, 111277.72011537934],
  [1752141649630, 111096.69668842915],
  [1752145408526, 111016.49778230184],
  [1752149033871, 111039.24103584772],
  [1752152632047, 110873.03110694999],
  [1752156248913, 110789.31246026137],
  [1752159799521, 111231.85985784495],
  [1752163411545, 111397.9336875094],
  [1752167030081, 112668.54314562622],
  [1752170614655, 113803.57940839755],
  [1752174231423, 113319.88143489836],
  [1752177791664, 113345.56264459594],
  [1752181344892, 113564.7644941765],
  [1752185001436, 116462.06669565785],
  [1752188629995, 116061.0328332691],
  [1752192208029, 115945.97312837391],
  [1752195765796, 115547.7141631778],
  [1752199405436, 115956.74521002891],
  [1752202950850, 116690.4881211946],
  [1752206593228, 116818.0495938592],
  [1752210224079, 116906.83517166134],
  [1752213824133, 118004.1499158492],
  [1752217451276, 117680.61824753445],
  [1752221020552, 117699.2703972958],
  [1752224602836, 118007.60380851576],
  [1752228238276, 118502.4306170008],
  [1752231757026, 118076.13750043296],
  [1752235459175, 117859.49747777793],
  [1752239030597, 117848.04110858658],
  [1752242603858, 117875.83779176614],
  [1752246132000, 117825.95947043467]],
 'market_caps': [[1751382199379, 2106603985235.5754],
  [1751385660193, 2108191628942.007],
  [1751389423274, 2111112339885.268],
  [1751393020774, 2112360786327.3298],
  [1751396624280, 2104535581777.5134],
  [1751400227235, 2099560497597.4563],
  [1751403681313, 2105981032969.7112],
  [1751407383098, 2104118404308.2537],
  [1751411075819, 2103087219499.2239],
  [1751414620619, 2100087563077.9324],
  [1751418214352, 2098315712249.7844],
  [1751421824475, 2102025960928.2756],
  [1751425407523, 2105205754271.191],
  [1751429016864, 2111648666896.0247],
  [1751432613161, 2115447790331.9062],
  [1751436215652, 2120437784461.012],
  [1751439824385, 2127626026412.19],
  [1751443397571, 2131192350622.273],
  [1751446957875, 2141760865892.0298],
  [1751450646622, 2140960261882.8032],
  [1751454033906, 2144176730421.1575],
  [1751458098708, 2137389161352.781],
  [1751461433908, 2135461480126.8083],
  [1751465042114, 2143130834397.0754],
  [1751468638496, 2148624543637.3398],
  [1751472245095, 2161721198923.963],
  [1751475840542, 2177777742501.521],
  [1751479456405, 2169412880728.343],
  [1751482892256, 2176813722173.7646],
  [1751486619434, 2177744260588.692],
  [1751490126451, 2173007010221.9814],
  [1751493832889, 2177479969109.0012],
  [1751497429210, 2171133029878.4612],
  [1751501037652, 2164664859776.4558],
  [1751504604369, 2167206505546.8174],
  [1751508210639, 2168962667353.7754],
  [1751511839165, 2161285404401.8765],
  [1751515447606, 2161832856549.0872],
  [1751519026793, 2165228673264.8699],
  [1751522638663, 2174824043340.3147],
  [1751526187470, 2177994156780.0935],
  [1751529648264, 2174279567725.4019],
  [1751533435412, 2177352013931.0156],
  [1751536945911, 2187768648360.0076],
  [1751540625434, 2184360782533.2185],
  [1751544224963, 2180741535732.1292],
  [1751547834603, 2168436319815.6716],
  [1751551432148, 2194226466797.0007],
  [1751555022935, 2182058577190.92],
  [1751558621741, 2171990821719.2925],
  [1751562237504, 2176232261282.8848],
  [1751565850945, 2179370920341.1328],
  [1751569413058, 2180583006487.6023],
  [1751572849130, 2183417684579.7134],
  [1751576534402, 2186032100290.0093],
  [1751580423581, 2184240817512.404],
  [1751583825545, 2182337316498.5544],
  [1751587427301, 2179664531219.9346],
  [1751591042281, 2178692263275.3994],
  [1751594616616, 2178823267063.1614],
  [1751598244301, 2172150054613.9294],
  [1751601826980, 2173319640325.5183],
  [1751605421725, 2168253774700.036],
  [1751609034555, 2169768287872.1099],
  [1751612626987, 2168228299258.4749],
  [1751616234841, 2163635483360.264],
  [1751619828086, 2164091267449.9814],
  [1751623352769, 2167254472626.2322],
  [1751627047047, 2166480428588.2502],
  [1751630625771, 2166687104600.2375],
  [1751634229513, 2163078988112.855],
  [1751637814783, 2152551512016.238],
  [1751641419941, 2145548901025.7795],
  [1751645049093, 2141543286321.4211],
  [1751648652227, 2141150640334.8647],
  [1751652227815, 2145922297835.6226],
  [1751655704764, 2140707573884.1404],
  [1751659437396, 2137520885796.114],
  [1751663036890, 2143141677024.2224],
  [1751666634074, 2146183006621.372],
  [1751670234072, 2152805812510.2366],
  [1751673839940, 2148447441304.9116],
  [1751677439910, 2152301716601.738],
  [1751680938155, 2147417711561.158],
  [1751684495201, 2149153043865.9592],
  [1751688221595, 2151620786858.2769],
  [1751691834549, 2152705775771.6104],
  [1751695420331, 2151031679620.527],
  [1751698916373, 2153018382603.121],
  [1751702606207, 2148677007055.261],
  [1751706087258, 2148136787562.2573],
  [1751709833677, 2149927586910.0083],
  [1751713419581, 2151616083855.8208],
  [1751717029684, 2151799289154.1267],
  [1751720620496, 2150849925916.687],
  [1751724208927, 2150758079283.2263],
  [1751727831772, 2151914279487.2546],
  [1751731408718, 2149476771215.0183],
  [1751735051791, 2149329645423.33],
  [1751738484124, 2149520598117.7437],
  [1751742229277, 2148219291394.5024],
  [1751745845024, 2150927826727.2612],
  [1751749405719, 2150168687467.984],
  [1751753016417, 2150113012352.5427],
  [1751756630380, 2151882351170.6257],
  [1751760237122, 2152281287061.9937],
  [1751763725859, 2152238962642.7786],
  [1751767395048, 2151626286380.696],
  [1751771032271, 2151266865028.5103],
  [1751774627687, 2149229466083.0574],
  [1751778045097, 2148179570860.9497],
  [1751781812460, 2148401917693.441],
  [1751785313067, 2151005636076.8274],
  [1751788872032, 2149305520579.314],
  [1751792623601, 2148662353322.4343],
  [1751796050016, 2146504585051.5088],
  [1751799729500, 2148259373624.4724],
  [1751803431499, 2149280653748.0203],
  [1751807023969, 2151895563904.9504],
  [1751810644610, 2165471878103.183],
  [1751814049792, 2164825654698.4849],
  [1751817822914, 2164700073208.4592],
  [1751821451508, 2165298240861.5728],
  [1751825034782, 2166150217249.2297],
  [1751828641993, 2156358603636.6968],
  [1751832234195, 2157739971777.9146],
  [1751835840385, 2162666190785.1072],
  [1751839381563, 2170811633929.2944],
  [1751842831172, 2173685739083.7993],
  [1751846610134, 2172228248277.911],
  [1751850233615, 2166319922801.6855],
  [1751853829846, 2168527577276.7642],
  [1751857419879, 2175912606865.8474],
  [1751861306141, 2176092850784.4607],
  [1751864614997, 2170707319099.8088],
  [1751868147940, 2169535196637.2273],
  [1751871698338, 2164041819287.785],
  [1751875413507, 2168622499867.862],
  [1751879018342, 2167704688518.1877],
  [1751882618255, 2164728603945.2993],
  [1751886274959, 2161838204924.5083],
  [1751889803015, 2160914479516.0957],
  [1751893426730, 2155731984128.7546],
  [1751897026463, 2153078533061.2505],
  [1751900445425, 2152427801938.6184],
  [1751904199912, 2155336410298.8848],
  [1751907827708, 2147967445928.0237],
  [1751911426215, 2147317002360.4458],
  [1751915031772, 2145329284526.501],
  [1751918641948, 2151098305609.8293],
  [1751922243764, 2146562465678.0337],
  [1751925823475, 2151497112174.7441],
  [1751929419629, 2148788653077.031],
  [1751933029854, 2153987517488.93],
  [1751936613192, 2154918039893.782],
  [1751940240840, 2145958364244.3008],
  [1751943799526, 2142267899450.415],
  [1751947428123, 2146450949950.4294],
  [1751951027424, 2147851985868.6694],
  [1751954616593, 2152160475369.8362],
  [1751958020004, 2154461552881.744],
  [1751961829826, 2156997201966.3933],
  [1751965388068, 2153711438802.669],
  [1751968965747, 2157217136884.5662],
  [1751972620158, 2164670103677.9192],
  [1751976230153, 2163390792637.5562],
  [1751979833973, 2166047154827.0117],
  [1751983245426, 2169050782889.0483],
  [1751987026192, 2158142057667.6567],
  [1751990639516, 2153088835912.7046],
  [1751994208603, 2156210071207.2373],
  [1751997846596, 2168566804089.8318],
  [1752001445284, 2170307806105.7432],
  [1752005042558, 2163635540342.8748],
  [1752008622474, 2162493460364.8643],
  [1752012184038, 2166544760999.5933],
  [1752015838904, 2166543478818.8232],
  [1752019436139, 2167014809947.8618],
  [1752023035281, 2167010201511.405],
  [1752026647713, 2163848496501.5261],
  [1752030196564, 2161443289026.5676],
  [1752033802905, 2155705982380.0022],
  [1752037370113, 2158712994668.3772],
  [1752040993182, 2163339052976.4856],
  [1752044636700, 2164714313288.7017],
  [1752048124359, 2162317923917.1587],
  [1752051627281, 2162165122551.504],
  [1752055255077, 2163396850911.422],
  [1752059005652, 2165199089198.3914],
  [1752062606517, 2169989791965.349],
  [1752066037275, 2176927576065.1296],
  [1752069838442, 2177620860341.3035],
  [1752073439773, 2163740487091.951],
  [1752076997051, 2168736691745.4827],
  [1752080604519, 2176188893841.551],
  [1752084231404, 2171381768556.3008],
  [1752087831035, 2178036162433.2144],
  [1752091427121, 2222599886688.838],
  [1752095020133, 2203625579181.9263],
  [1752098597685, 2207796809456.288],
  [1752102230288, 2214757427001.366],
  [1752106089165, 2213877968415.5825],
  [1752109421919, 2208921640875.344],
  [1752113036247, 2213958011121.8574],
  [1752116621604, 2212740582774.217],
  [1752120223801, 2209252304351.874],
  [1752123820774, 2211216214712.598],
  [1752127434856, 2209611242226.0713],
  [1752131038190, 2213149663255.675],
  [1752134460301, 2213042821260.081],
  [1752138214712, 2213793670350.5063],
  [1752141649630, 2210103728885.121],
  [1752145408526, 2207284934205.963],
  [1752149033871, 2209084701102.132],
  [1752152632047, 2205085116599.102],
  [1752156248913, 2203764778152.905],
  [1752159799521, 2212010955573.2812],
  [1752163411545, 2215412791928.693],
  [1752167030081, 2240505433318.0146],
  [1752170614655, 2263082737646.8193],
  [1752174231423, 2253318945220.277],
  [1752177791664, 2253240511078.4346],
  [1752181344892, 2258614181012.73],
  [1752185001436, 2316494094865.0493],
  [1752188629995, 2308585167780.5557],
  [1752192208029, 2305557087070.3257],
  [1752195765796, 2299093663538.248],
  [1752199405436, 2306481612508.9],
  [1752202950850, 2320685520748.159],
  [1752206593228, 2323487043405.801],
  [1752210224079, 2323708796617.2134],
  [1752213824133, 2348505162336.2954],
  [1752217451276, 2343722137849.2363],
  [1752221020552, 2342459567799.279],
  [1752224602836, 2347324732632.9243],
  [1752228238276, 2357891795993.519],
  [1752231757026, 2349488406199.456],
  [1752235459175, 2344730808271.2656],
  [1752239030597, 2343696745539.378],
  [1752242603858, 2343199516879.124],
  [1752246132000, 2342722660814.455]],
 'total_volumes': [[1751382199379, 21887101739.91564],
  [1751385660193, 24352624243.54862],
  [1751389423274, 24031235865.680534],
  [1751393020774, 24031613830.070282],
  [1751396624280, 24232574407.89782],
  [1751400227235, 24733517828.086845],
  [1751403681313, 25305645433.927773],
  [1751407383098, 25144379019.546047],
  [1751411075819, 25106725388.894093],
  [1751414620619, 25091393876.20341],
  [1751418214352, 24877294832.67813],
  [1751421824475, 25331846752.471447],
  [1751425407523, 25135944489.52843],
  [1751429016864, 25491216915.50663],
  [1751432613161, 25827486209.318245],
  [1751436215652, 25859918335.713837],
  [1751439824385, 26326373079.731834],
  [1751443397571, 26595762551.14098],
  [1751446957875, 27874857246.915386],
  [1751450646622, 27911261327.236843],
  [1751454033906, 27482094200.26944],
  [1751458098708, 28029369472.178745],
  [1751461433908, 28220640665.5678],
  [1751465042114, 25434868475.919647],
  [1751468638496, 24455995598.67598],
  [1751472245095, 27386080502.58191],
  [1751475840542, 31409622431.881046],
  [1751479456405, 32697950441.030052],
  [1751482892256, 33691580791.754154],
  [1751486619434, 34380192772.13691],
  [1751490126451, 34491554481.329765],
  [1751493832889, 35308963955.68726],
  [1751497429210, 32949099684.148376],

In [20]:
btc_data = btc_data['prices']
data = pd.DataFrame(btc_data, columns=['TimeStamp', 'Price'])
data

         TimeStamp          Price
0    1751382199379  105922.447876
1    1751385660193  105993.553309
2    1751389423274  106118.542473
3    1751393020774  106274.384018
4    1751396624280  105781.269134
..             ...            ...
236  1752231757026  118076.137500
237  1752235459175  117859.497478
238  1752239030597  117848.041109
239  1752242603858  117875.837792
240  1752246132000  117825.959470

[241 rows x 2 columns]

In [21]:
data['Date'] = pd.to_datetime(data['TimeStamp'], unit='ms')
data

         TimeStamp          Price                    Date
0    1751382199379  105922.447876 2025-07-01 15:03:19.379
1    1751385660193  105993.553309 2025-07-01 16:01:00.193
2    1751389423274  106118.542473 2025-07-01 17:03:43.274
3    1751393020774  106274.384018 2025-07-01 18:03:40.774
4    1751396624280  105781.269134 2025-07-01 19:03:44.280
..             ...            ...                     ...
236  1752231757026  118076.137500 2025-07-11 11:02:37.026
237  1752235459175  117859.497478 2025-07-11 12:04:19.175
238  1752239030597  117848.041109 2025-07-11 13:03:50.597
239  1752242603858  117875.837792 2025-07-11 14:03:23.858
240  1752246132000  117825.959470 2025-07-11 15:02:12.000

[241 rows x 3 columns]